SEMANTIC_MAP = {
    "buildings": {
        "palace",
        "bell cote",
        "monastery",
        "church",
        "cinema",
        "mobile home",
        "prison",
        "castle",
        "library",
        "mosque",
        "planetarium",
        "dome",
        "triumphal arch",
        "lumbermill",
        "greenhouse",
        "solar dish",
        "obelisk",
        "boathouse",
    },
    "sea": {
        "seashore",
        "lakeside",
        "sandbar",
        "breakwater",
        "dock",
        "beacon",
        "pier",
        "drilling platform",
        "speedboat",
        "fireboat",
        "canoe",
        "submarine",
        "killer whale",
        "grey whale",
        "schooner",
        "catamaran",
    },
    "forest": {
        "worm fence",
        "stone wall",
        "park bench",
        "suspension bridge",
        "park bench",
    },
    "glacier": {
        "ski",
        "snowmobile",
        "dogsled",
        "snowplow",
        "ice bear",
        "promontory",
    },
    "street": {
        "streetcar",
        "traffic light",
        "jinrikisha",
        "cab",
        "trailer truck",
        "street sign",
        "trolleybus",
        "unicycle",
    },
    "mountain": {
        "alp",
        "valley",
        "cliff",
        "volcano",
        "mountain tent",
        "cliff dwelling",
        "geyser",
        "mountain bike",

    },
}


THESIS_CLASSES = [
    "buildings",
    "forest",
    "glacier",
    "mountain",
    "sea",
    "street",
]